config/routes.rb
Rtevent::Application.routes.draw do
  devise_for :users
  
  resources :events do
  	resources :comments, only: [ :index, :create ]
  end
  
  resources :places

  get '/token' => 'home#token', as: :token
  get '/about' => 'home#about', as: :about
  resources :home, only: :index
  

  root 'home#index'

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user, dependent: :destroy
  belongs_to :event, dependent: :destroy

	def self.for_event event_id
		data = Comment.where(event_id: event_id).includes(:user).order(created_at: :desc)
		filtered_data = data.select(:id, :content, :user_id).as_json(:include => {:user => {:only => [:username]}})			#	takes only what is needed, since it's used for creating a JSON response

		filtered_data
	end
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :place
  belongs_to :user
  has_many :comments
  
  validates :title, :presence => true
  validates :user_id, :presence => true
  validates :place_id, :presence => true

  paginates_per 9

  def upcoming? 
    DateTime.now < starts_at
  end

  def past? 
    !upcoming?
  end

end

app/models/place.rb
class Place < ActiveRecord::Base
	has_many :events, dependent: :destroy
	
	paginates_per 5
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, :presence => true, :uniqueness => true  

  has_many :comments
  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
	skip_before_filter :verify_authenticity_token				#	FIXME: This needs to be removed. Secure vulnerability

  respond_to :json

  def index
		id = params[:event_id]
		@comments = {'comments' => Comment.for_event(id) }
		render json: @comments
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.save
    head :created
  end

  private

    def comment_params
      params.require(:comment).permit(:user_id, :event_id, :content)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_event, only: [:show, :edit, :update, :destroy]

	respond_to :html, :json

  # GET /events
  # GET /events.json
  def index
    @events = Event.page(params[:page])
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :starts_at, :place_id, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :authenticate_user!, only: :token

	def index
	end

	def about
	end

	def token
	end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.page(params[:page])
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)
    
    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render action: 'show', status: :created, location: @place }
      else
        format.html { render action: 'new' }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:place_name, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper

def hot_events
	events = Event.all
	
	events.select{|event| event.starts_at > Time.now}.sort[0..4]		#nearest five future events	
end

end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Event</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user %></td>
        <td><%= comment.event %></td>
        <td><%= comment.content %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Event:</strong>
  <%= @comment.event %>
</p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div id="starts_at" class="field">
    <%= f.label :starts_at %><br>
    <%= f.datetime_select :starts_at %>
  </div>
  <div class="field">
    <%= f.label :place %><br>
    <%= f.select :place_id, options_from_collection_for_select(Place.all, :id, :place_name, @event.place_id) %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<div class="row">
	<% @events.each do |event| %>
		<%= content_tag_for(:div, event, :class => "col-xs-6 col-lg-4") do %>
		  <h2><%= event.title %></h2>
		  <p><%= event.description %></p>
		  <p><%= link_to 'Details', event, :class => 'btn btn-default' %>
		  	<%= link_to 'Edit', edit_event_path(event)%>
		  	<%- if event.user_id == current_user.id %>
		  		<%= link_to 'Delete', event, :method => :delete, :data => { :confirm => 'Are you sure?' } %>
		  	<% end %>
		  </p>
		<% end %>

	    
	    
	<% end %>
</div>
<%= paginate @events %>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Starts at:</strong>
  <%- unless @event.starts_at.to_date == Date.today %>
  	<%= @event.starts_at.strftime("%A, %B %d, %Y") %>
  <%- else %>
  	<%= distance_of_time_in_words(Time.now, @event.starts_at) %>
  <% end %>
</p>

<p>
  <strong>Place:</strong>
  <%= @event.place.place_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>
<p>
	Posted by: <%= @event.user.username %> at <%= @event.created_at.strftime('%B %d, %Y') %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>


<div class="row" ng-app="commentMaintainer">
    <div class="col-md-8" ng-controller="CommentController" ng-init="init(<%= @event.id %>)">
		    <div class="page-header">
		      <h1><small class="pull-right">{{ numberOfComments }} comments</small> Comments </h1>
		    </div> 
		     <div class="comments-list">
		         <div class="media" ng-repeat="comment in comments">
		              <div class="media-body">
		                  
		                <h4 class="media-heading user_name">{{ comment.user.username }}</h4>
		                <p>{{ comment.content }}</p>
		                
		                <br />
		              </div>
		         </div>
		     </div>
		     <br />
      <div class="col-md-8" >
			<div class="widget-area no-padding blank">
				<div class="status-upload">
					<form class="form-horizontal">
						<div class="form-group">
							<textarea class="form-control" rows="7" ng-model="commentText"></textarea>
						</div>
						<button type="button" class="btn btn-primary" ng-click="comment('<%= current_user.id %>', '<%= @event.id %>'); refreshStream()">Leave a comment</button>
					</form>
				</div><!-- Status Upload  -->
			</div><!-- Widget Area -->
		</div>
   </div>
</div>        

app/views/home/index.html.erb
<h2>Hot events</h2>
<br />

<table class="table table-striped">
  <tbody>
    <% hot_events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td>  <%- unless event.starts_at.to_date == Date.today %>
                <%= event.starts_at.strftime("%A, %B %d, %Y") %>
              <%- else %>
                <%= distance_of_time_in_words(Time.now, event.starts_at) %>
              <% end %>
        </td>
        <td><%= event.place.place_name %></td>
        <td><%= event.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rtevent</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <nav class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
        <div class="navbar-header"> 
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
             <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span>
             <span class="icon-bar"></span><span class="icon-bar"></span>
          </button> <%= link_to 'RTEvent', root_path, :class => "navbar-brand" %>
        </div>
        
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <% if user_signed_in? -%>
              <li>
                <%= link_to 'Events', events_path %>
              </li>
              <li>
                <%= link_to 'Places', places_path %>
              </li>
            <% end %>
            <li>
              <%= link_to 'About', about_path %>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
              <% unless user_signed_in? -%>
                <li>
                    <%= link_to 'Sign up', new_user_registration_path %>
                  </li>
                  <li>
                    <%= link_to 'Login', new_user_session_path %>
                </li>
              <% else -%>
                <li>
                  <%= link_to 'Logout', destroy_user_session_path, :method => :delete %>
                </li>
              <% end -%>
              <li>
                <span>&nbsp;&nbsp;&nbsp;</span>   <!-- I'm a terrible person -->
              </li>
          </ul>
        </div>
        
      </nav>
      
      <div class="content">
        <p id="notice"><%= notice %></p>
  
        <%= yield %>
      </div>
      
    </div>
  </div>
</div>


</body>
</html>

app/views/places/_form.html.erb
<%= form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :place_name %><br>
    <%= f.text_field :place_name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing place</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<h1>Listing places</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Place name</th>
      <th>Address</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <%= content_tag_for(:tr, place) do %>
        <td><%= place.place_name %></td>
        <td><%= place.address %></td>
        <td><%= link_to 'Show', place %></td>
        <td><%= link_to 'Edit', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    <% end %>
  </tbody>
</table>

<%= paginate @places %>
<br>

<%= link_to 'New Place', new_place_path %>

app/views/places/new.html.erb
<h1>New place</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p>
  <strong>Place name:</strong>
  <%= @place.place_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @place.address %>
</p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>
<br />
<br />

<h2>Incoming events</h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Starts at</th>
      <th>Place</th>
      <th>Description</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @place.events.select do |event| if event.starts_at >= DateTime.now %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.starts_at %></td>
        <td><%= event.place.place_name %></td>
        <td><%= event.description %></td>
        <td><%= link_to 'Show', event %></td>
      </tr>
      <%end %>
    <% end %>
  </tbody>
</table>

<br />
<br />

<h2>Past events</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Starts at</th>
      <th>Place</th>
      <th>Description</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @place.events.select do |event| if event.starts_at < DateTime.now %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.starts_at %></td>
        <td><%= event.place.place_name %></td>
        <td><%= event.description %></td>
        <td><%= link_to 'Show', event %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>